русификатор эррорки
Huz2e/massmeta pull request #118
Opened 2024-06-22 23:21 UTC by MelokG000

## About The Pull Request

удаляем пиндосский ERROR, делаем наш БЛЯТЬ
![error2](https://github.com/Huz2e/massmeta/assets/99420088/8a6c872f-6fb4-49c8-b6e0-f8dfa15e79bc)

## Why It's Good For The Game

русское - хорошее

## Changelog

:cl:
image: кому нужна эррорка когда мы можем БЛЯТЬ
/:cl:

2024-06-22 23:22 UTC, xKREKSx commented
НАШ СЛОН🐘

2024-06-23 06:41 UTC, Artemchik542 commented
Так этот спрайт ошибки по спрайтам разбросан всюду, твой пиар вообще что-то изменит?

2024-06-23 08:11 UTC, homexp13 commented on icons/obj/fluff/general.dmi
корневые dmi файлы не меняем, переопределяем модульно по возможности

2024-06-23 08:13 UTC, homexp13 requested changes
ну как написал собственно

2024-06-24 08:45 UTC, Huz2e commented on icons/obj/fluff/general.dmi
нельзя изменять файлы ТГшные, сделай свой

2024-06-24 12:36 UTC, closed without merging