Система тестов для модульных файлов (раунд 2)
Huz2e/massmeta pull request #140
Opened 2024-06-28 07:31 UTC by Artemchik542

## About The Pull Request
Попытка починить систему тестов для наших модульных файлов

## Why It's Good For The Game
Тестировать модульную папку тоже надо

## Changelog

:cl:
/:cl:

2024-06-28 20:28 UTC, assaultmachine requested changes
говно, переделывай

2024-06-30 13:59 UTC, Artemchik542 commented
> говно, переделывай

увы

2024-06-30 14:34 UTC, Huz2e approved these changes

2024-07-01 10:16 UTC, Artemchik542 commented
У меня локально все сломалось, открою в виде нового пиара

2024-07-01 10:16 UTC, closed without merging