Портирует Наниты с Манки Стейшена.
Huz2e/massmeta pull request #73
Opened 2024-02-07 05:00 UTC by Xackii

## About The Pull Request

 Я не шучу он реально портирует наниты с манки стейшена.

## Why It's Good For The Game

 Нёрды поймут 

:cl:
add: Добавлены наниты с манки стейшена
/:cl:

2024-02-07 10:08 UTC, homexp13 commented on icons/mob/huds/hud.dmi
и не понятно кстати зачем два hud.dmi в корне и модульной папке

2024-02-07 10:09 UTC, homexp13 commented on code/game/machinery/computer/crew.dm
Сомнительно, но окей

2024-02-07 12:31 UTC, Xackii commented on massmeta/code/datums/nanits/_nanites_defines.dm
отправил сигналы и дефайны в массмета инклюд

2024-02-07 12:32 UTC, Xackii commented on tgstation.dme
> +#include "massmeta\code\datums\nanits\nanites_research\nanite_programs\weapon.dm"
сигналы и дефайны записанны в инклюд остальные файлы оставшиеся в модулях иницилизируются в коре

2024-02-07 12:33 UTC, Xackii commented on code/game/data_huds.dm
> +	hud_icons = list(STATUS_HUD, HEALTH_HUD, NANITE_HUD)
подписал

2024-02-07 12:33 UTC, Xackii commented on code/__DEFINES/atom_hud.dm
> +
перекинул всё в одну папку с дефайнами нанитов отправил в массмета инклюд

2024-02-07 12:33 UTC, Xackii commented on icons/obj/machines/nanites.dmi
переместил

2024-02-07 18:30 UTC, Xackii commented on icons/mob/huds/hud.dmi
скопи пастил с гитхаба. сам файл ничем не отличается(проблемы с байтиками/разрешениями). Если опять конфликты вызывает то пиздец

2024-02-07 18:30 UTC, Xackii commented on code/game/objects/items/pinpointer.dm
> +			return TRUE
пометил пись пись

2024-02-07 18:31 UTC, Xackii commented on tgstation.dme
> +#include "massmeta\code\datums\nanits\nanites_research\nanite_programs\weapon.dm"
перекинул в инклюд дм

2024-02-07 18:31 UTC, Xackii commented on code/__DEFINES/traits/declarations.dm
> +
нужно

2024-02-07 18:31 UTC, Xackii commented on code/__DEFINES/~massmeta_defines/_defines_include.dm
> +#include "nanites_signals.dm"
поправил

2024-02-09 14:52 UTC, homexp13 approved these changes

2024-02-09 18:55 UTC, homexp13 requested changes
![image](https://github.com/Huz2e/massmeta/assets/52973135/5f57a6e8-05f3-41e1-94b6-c4409e939709)
так тут хуйня

2024-02-09 19:55 UTC, homexp13 commented
о уже конфликты пошли clueless

2024-02-10 03:31 UTC, Xackii commented
> ![image](https://private-user-images.githubusercontent.com/52973135/303748839-5f57a6e8-05f3-41e1-94b6-c4409e939709.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MzYxNDUsIm5iZiI6MTcwNzUzNTg0NSwicGF0aCI6Ii81Mjk3MzEzNS8zMDM3NDg4MzktNWY1N2E2ZTgtMDVmMy00MWUxLTk0YjYtYzQ0MDllOTM5NzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDAzMzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNzIyZjdhYTY4NTc1OGZjOGYyMzg2Y2I5Nzc2MThkODFiZDZlNjBiMTM3OTEzNmM3ODk5ZGYxNTBiY2ZiYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hPYHAxF-MvLKp08qEhCOAClYCFAi2dB60Xx_pG-8f30) так тут хуйня

На это вроде похуй. Но ща посмотрим

2024-02-11 13:21 UTC, merged